targets:
  $default:
    builders:
      code_generation|topLevelNamesBuilder:
        generate_for:
          - lib/example/*.dart
        enabled: True

  # The next three builders are `SharedPartBuilder` instances.
  # Notice they each have
  # `build_extensions` set to a `NAME.g.part` file.
  #    NAME corresponds to the second argument to the SharedPartBuilder ctor.
  #    `.g.part` is the extension expected of SharedPartBuilder.
  # `build_to: cache` - the output is not put directly into the project
  # `applies_builders` - uses the `combining_builder` from `source_gen` to
  #   combine the parts from each builder into one part file.

builders:
  topLevelNamesBuilder:
    import: 'package:code_generation/code_generation.dart'
    builder_factories: [ 'topLevelNamesBuilder' ]
    build_extensions: {".dart": ["topLevelNames.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]